# Note: The workflow needs at least permissions to create and approve pull requests, and maybe R/W on all repos in scope?
# Change under Settings > Actions > General and then Workflow permissions
name: Sync Fork

on:
  schedule:
    - cron: '*/15 9-12 * * 5' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: herrbengtsson
          repo: ezine-test
          base: main
          head: main
          ignore_fail: true
          retries: 1
